# Generated by Django 3.2.7 on 2022-08-22 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('cedula', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=25)),
                ('segundo_nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('primer_apellido', models.CharField(max_length=25)),
                ('segundo_apellido', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('etnia', models.CharField(choices=[('M', 'Mestizo'), ('C', 'Creole'), ('MK', 'Miskitu'), ('U', 'Ulwa'), ('R', 'Rama'), ('G', 'Garifuna')], max_length=15)),
                ('direccion', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Formato: 8888-8888', max_length=9)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suir.institucion')),
                ('usuario', models.OneToOneField(limit_choices_to={'groups__name__contains': 'funcionarios_publicos', 'is_active': True}, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institucion', 'usuario'],
            },
        ),
        migrations.CreateModel(
            name='Contribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('M', 'Monetaria'), ('Mx', 'Medicinas'), ('P', 'Provisiones'), ('Ps', 'Pasajes'), ('Mt', 'Materiales de Construcción'), ('A', 'Articulos Escolares'), ('O', 'Otro')], max_length=2)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('concepto', models.CharField(max_length=150)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='contribuciones', to='hamster.beneficiario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hamster.funcionario')),
            ],
            options={
                'verbose_name_plural': 'Contribuciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
