# Generated by Django 3.2.7 on 2022-08-22 22:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suir', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'sectores')), on_delete=django.db.models.deletion.RESTRICT, related_name='bonos_sectores', related_query_name='bono_sector', to='suir.detalletabla')),
                ('tipo', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'tipos_bono')), on_delete=django.db.models.deletion.RESTRICT, related_name='bonos_tipos', related_query_name='bono_tipo', to='suir.detalletabla')),
            ],
            options={
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('acronimo', models.CharField(max_length=45, verbose_name='Acrónimo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('finalizado', models.BooleanField(default=False)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suir.institucion')),
                ('sector', models.ForeignKey(blank=True, limit_choices_to=models.Q(('tabla__tabla', 'sectores')), null=True, on_delete=django.db.models.deletion.RESTRICT, to='suir.detalletabla')),
            ],
            options={
                'ordering': ['finalizado', 'sector', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Protagonista',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cedula', models.CharField(help_text='Cédula de identidad sin guiones', max_length=14, primary_key=True, serialize=False, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, help_text='8888-8888', max_length=9, null=True, verbose_name='Teléfono')),
                ('promotor', models.BooleanField(default=False, verbose_name='Es Promotor')),
                ('jvc', models.BooleanField(default=False, verbose_name='Miembro de JVC')),
                ('comunidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suir.comunidad')),
                ('etnia', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'etnias')), on_delete=django.db.models.deletion.RESTRICT, to='suir.detalletabla')),
            ],
            options={
                'verbose_name': 'Protagonista',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cedula', models.CharField(help_text='Cédula de identidad sin guiones', max_length=14, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], max_length=1)),
                ('telefono', models.CharField(blank=True, help_text='8888-8888', max_length=9, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('comunidad', models.ForeignKey(help_text='Comunidad de residencia', on_delete=django.db.models.deletion.RESTRICT, to='suir.comunidad')),
                ('etnia', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'etnias')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_etnias', related_query_name='contacto_etnia', to='suir.detalletabla')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suir.institucion')),
                ('usuario', models.ForeignKey(help_text='Requerido sólo si el usuario tendrá acceso a digitar o extraer datos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institucion', 'apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200)),
                ('acronimo', models.CharField(max_length=45, verbose_name='Acrónimo')),
                ('descripcion', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Descripción')),
                ('finalizado', models.BooleanField(default=False)),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='suir.contacto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='suir.institucion')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sispro.programa')),
                ('sector', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'sectores')), on_delete=django.db.models.deletion.RESTRICT, to='suir.detalletabla')),
            ],
            options={
                'ordering': ['finalizado', 'sector', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProtagonistaBono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_recibido', models.DateField(help_text='Fecha en que recibió el Bono/Plan de inversión.')),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('entregado', models.BooleanField(default=False, help_text='El Bono/Plan de inversión se entregó al protagonista.')),
                ('activo', models.BooleanField(default=True, help_text='Está activo para seguimiento.')),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protagonista_bono_actualizador', to=settings.AUTH_USER_MODEL)),
                ('bono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispro.bono')),
                ('comunidad', models.ForeignKey(help_text='Comunidad donde se ejecuta.', on_delete=django.db.models.deletion.PROTECT, to='suir.comunidad')),
                ('digitador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protagonista_bono_digitador', to=settings.AUTH_USER_MODEL)),
                ('protagonista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sispro.protagonista')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sispro.proyecto')),
                ('tecnico', models.ForeignKey(help_text='Técnico que realizó la entrega.', null=True, on_delete=django.db.models.deletion.RESTRICT, to='sispro.tecnico')),
            ],
            options={
                'verbose_name': 'Protagonista con Bono/Plan',
                'verbose_name_plural': 'Protagonistas con Bonos/Planes',
                'ordering': ['protagonista', '-fecha_recibido', 'bono'],
            },
        ),
        migrations.CreateModel(
            name='Capitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cantidad', models.FloatField()),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo en Córdobas(C$)', max_digits=8, verbose_name='Costo unitario')),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Costo total en Córdobas(C$)', max_digits=10, verbose_name='Costo total')),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalizacion_actualizador', to=settings.AUTH_USER_MODEL)),
                ('articulo', models.ForeignKey(limit_choices_to=models.Q(('tabla__tabla', 'articulos')), on_delete=django.db.models.deletion.RESTRICT, related_name='capitalizaciones_articulos', to='suir.detalletabla')),
                ('digitador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalizacion_digitador', to=settings.AUTH_USER_MODEL)),
                ('p_bono', models.ForeignKey(limit_choices_to=models.Q(('bono__tipo__elemento', 'plan_inversion')), on_delete=django.db.models.deletion.CASCADE, to='sispro.protagonistabono')),
                ('unidad', models.ForeignKey(help_text='Unidad de Medida', limit_choices_to=models.Q(('tabla__tabla', 'unidades')), on_delete=django.db.models.deletion.RESTRICT, related_name='capitalizaciones_unidades', to='suir.detalletabla')),
            ],
            options={
                'ordering': ['p_bono'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tema', models.CharField(max_length=150, verbose_name='Tema de la capacitación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_final', models.DateField(verbose_name='Fecha de culminación')),
                ('bono', models.ForeignKey(help_text='Bono/Plan correspondiente a la capacitación.', on_delete=django.db.models.deletion.RESTRICT, to='sispro.bono')),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='suir.comunidad')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('protagonista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sispro.protagonista')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'ordering': ['protagonista', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('mes', models.CharField(choices=[('1', 'ENE'), ('2', 'FEB'), ('3', 'MAR'), ('4', 'ABR'), ('5', 'MAY'), ('6', 'JUN'), ('7', 'JUL'), ('8', 'AGO'), ('9', 'SEP'), ('10', 'OCT'), ('11', 'NOV'), ('12', 'DIC')], max_length=2, verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto C$')),
                ('digitador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('p_bono', models.ForeignKey(limit_choices_to={'bono__tipo__elemento': 'plan de inversion'}, on_delete=django.db.models.deletion.CASCADE, to='sispro.protagonistabono')),
                ('tipo', models.ForeignKey(help_text='Tipo de aporte', on_delete=django.db.models.deletion.RESTRICT, to='suir.detalletabla')),
            ],
            options={
                'ordering': ['p_bono', 'anio', 'mes'],
            },
        ),
    ]
