# Generated by Django 3.2.7 on 2021-11-03 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0002_transmision'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmision',
            name='origen',
            field=models.CharField(choices=[('yt', 'YouTube'), ('fb', 'Facebook')], default='yt', max_length=2),
        ),
        migrations.AlterField(
            model_name='transmision',
            name='codigo',
            field=models.TextField(help_text='Código Embed </> o Insertar.', validators=[django.core.validators.RegexValidator(message='El campo debe contener el código <embed> de YouTube.', regex='<iframe')], verbose_name='Codigo de YouTube'),
        ),
    ]
