# Generated by Django 3.2.7 on 2022-01-15 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suir', '0004_alter_transmision_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
