# -*- coding: utf-8 -*-
"""
Django settings for portal_graccs project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-sd96t)4^zdoe%v#p7r6fxo9f)t3@6xykg$hux66eb*6y5jkrqq'
SECRET_KEY = 'b)hexga=ln#ufwh$3*n@oqpeoe^+gkoq209pb#vrj6qf^)+17q'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = True

ALLOWED_HOSTS = ['si.graccs.gob.ni','200.30.128.97','localhost','127.0.0.1','[::1]','facebook.com']

X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin.apps.SimpleAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_filters',
    'rest_framework',
    'rest_framework_gis',
    'rest_framework.authtoken',
    'django_bootstrap5',
    'django_bootstrap_icons',
    'corsheaders',
    'suir',
    'sispro',
    'hamster',
    'ckeditor',
    'ckeditor_uploader',
    'hitcount',
    'django_social_share'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
            'http://si.graccs.gob.ni',
            'http://si.graccs.gob.ni:8000',
            'http://localhost',
            'http://localhost:8000',
            'http://127.0.0.1',
            'http://127.0.0.1:8000',
        ]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'portal_graccs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_graccs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'portal_graccs',
        'USER': 'portalgraccsuser',
        'PASSWORD': 'n?u{F4yp^F8>r?$8',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Managua' #'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_URL = 'http://si.graccs.gob.ni/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# Media upload storage

MEDIA_URL = '/media/'
# MEDIA_URL = 'http://si.graccs.gob.ni/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Configuraciones de Django Rest_Framework

REST_FRAMEWORK = {

    # Usamos los permisos estándar de Django de django.contrib.auth,
    # o damos acceso de solo lectura a usuarios no autenticados.

    #'DEFAULT_PERMISSION_CLASSES' : [
    #    'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    #]
    'DEFAULT_PERMISSION_CLASSES' : [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_AUTHENTICATION_CLASSES' : [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuraciones de CKEditor

CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/'

CKEDITOR_UPLOAD_PATH = 'ckeditor/'

CKEDITOR_IMAGE_BACKEND = 'pillow'

CKEDITOR_THUMBNAIL_SIZE = (75, 75)

CKEDITOR_RESTRICT_BY_USER = True

CKEDITOR_BROWSE_SHOW_DIRS = True

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic'],
        ],
        'toolbar_SuirToolbar': [
            {'name': 'document', 'items': ['Source', '-', 'Preview']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            '/',
            {'name': 'basicStyles', 'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'paragraph', 'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
            'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert', 'items': ['Image','Image2', 'Embed', 'Youtube', 'Table', 'HorizontalRule', 'SpecialChar']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
        ],
        'toolbar': 'SuirToolbar',
        'tabSpaces': 4,
        'height': 291,
        'width': '100%',
        'removePlugins': 'stylesheetparser',
        'allowedContent': True,
        'extraAllowedContent': 'iframe[*]',
        'extraPlugins': ','.join([
            'autolink',
            'autoembed',
            'clipboard',
            'dialog',
            'dialogui',
            'embedsemantic',
            'image2',
            'iframe',
            'iframedialog',
            'language',
            'uploadimage',
            'widget',
            'youtube',
            ]),
    }
}

SUIR_CONF = {
    'paginas': 12,
}

HITCOUNT_KEEP_HIT_ACTIVE = {'hours':12}

HITCOUNT_HITS_PER_IP_LIMIT = 0

SISPRO_CONF = {
        'paginas': 20,
        'tipos-error': [
            'error de validación',
            'acceso denegado',
            'permisos de usuario',
            'propiedad de registro',
            ],
        'mensajes-error': {
            'validacion': "la sesión ha expirado. por favor, ingrese nuevamente con su nombre de usuario y contraseña.",
            'acceso': "Usted no tiene acceso para ejecutar la operación solicitada.",
            'permisos': "Su usuario no cuenta con los permisos para realizar la operación solicitada. Consulte con el administrador del sistema.",
            'propietario': "Usted no es el propietario/digitador del registro. Por este motivo, no tiene permiso de modificación. Consulte con el administrador del sistema.",
            }
        }
